### PR TITLE
Adds Latvian Wikipedia (lvwiki) support and Latvian translation

### PR DESCRIPTION
**Pull request by papuass**

### CODE REVIEW

**Comment by papuass** [comment]
@googlebot I signed it!

**Comment by xinbenlv** [comment]
This is awesome @papuass. Just one thing, ***could you consolidate #154 and #155 into one PR?***
The reason I ask you this is that  we expect there will be more than several dozens of PR for adding language support. Therefore, we hope each language support PR to be self-contained and can be used as a reference commit.

**Comment by papuass** [comment]
@xinbenlv I have consolidated everything into this pull request.

**Comment by hrasyid** [comment]
@papuass  I think you need to update a few more files, e.g. to specify the domain name of Latvian Wikipedia. See https://github.com/google/wikiloop-battlefield/pull/133/files for a recent example.
Also, you can use the "Deploy to Heroku" button in your branch (https://github.com/papuass/wikiloop-battlefield/tree/patch-1) to have your own instance of the website and test whether you patch have worked.

**Comment by xinbenlv** [comment]
Thank you @papuass for this Pull Request. I have deployed a Heroku Review App for this PR (it should have been deployed automatically, I am pinging Heroku support team currently.). You can check the review app for a demo of your change. 

Like @hrasyid said, it seems there are a few changes in #133 that this PR lacks. For [example](https://github.com/hrasyid/wikiloop-battlefield/blob/0b67e37c6ab3ecd40605ca950818257be1c16cd7/layouts/default.vue#L112
) the changes in  `layouts/default.vue` is not there in this PR





Therefore I assume based on the code's behavior, the new language will not yet
 show up in the language switch dropdown.

**Comment by papuass** [comment]
I think I have completed the changes.
Also managed to set up Heroku account (need to authorize it with credit card to launch with Mongo plugin) and deployed my branch.

**Comment by xinbenlv** [comment]
Good job.

>Also managed to set up Heroku account (need to authorize it with credit card to launch with Mongo plugin) and deployed my branch.

By the way you don't have to create a Heroku account / authorzie with your credit card, This project has been setup to create Heroku Review App so you don't have to, but it's good that you created one, just like @hrasyid 

Again, thank you for the contribution and welcome to the contributors of WikiLoop, @papuass

**Pull request merged**
