### PR TITLE
Enable support for Turkish wikipedia

### PR DESCRIPTION
**Pull request by xinbenlv**

### CODE REVIEW

**Comment by xinbenlv** [comment]
@aligoren could you help take a look?

**Comment by aligoren** [comment]
Yes, I will. Sorry, we're in a different timezone. I saw now.

**Comment by xinbenlv** [comment]
@aligoren thank you for making this possible. I have just pushed it onto production. You shall be able to see it on battlefield.wikiloop.org now. I have also shared this to Facebook https://www.facebook.com/groups/wikipediaweekly/ 

The next question of this issue is: could we ask some Turkish speaker to testout how well this feature works for them?

**Comment by aligoren** [comment]
> @aligoren thank you for making this possible. I have just pushed it onto production. You shall be able to see it on battlefield.wikiloop.org now. I have also shared this to Facebook https://www.facebook.com/groups/wikipediaweekly/

Thank you 😎

> The next question of this issue is: could we ask some Turkish speaker to testout how well this feature works for them?

I can ask my friends. I'm not sure they'll accept. Do you know Turkish people to test it? Except for me :)

**Pull request merged**
