### PR TITLE
Move to dicebear identicon

### PR DESCRIPTION
**Pull request by FlorianKoerner**
See also #162

### CODE REVIEW

**Comment by FlorianKoerner** [comment]
@googlebot I signed it!

**Comment by xinbenlv** [comment]
@FlorianKoerner it works, thank you for your PR!

**Comment by xinbenlv** [comment]
@FlorianKoerner it's great to have DiceBear/avatar author to commit a PR for us, thank you!

By the way, does DiceBear provide batch API?

**Comment by FlorianKoerner** [comment]
What exactly do you have in mind? In what context do you want that?

**Comment by xinbenlv** [comment]
Such as this leaderboard, we display avatar of many users on the same screen and we felt that the latency of querying avatar might impact your server, but also our user experience.

http://canary.battlefield.wikiloop.org/leaderboard

**Comment by xinbenlv** [comment]
This is launched at Live

**Comment by FlorianKoerner** [comment]
Why do you create the avatars on the server side and not in the browser? The page loads very slowly.

If you want to use the HTTP-API of DiceBear, you don't have to worry about the latency. DiceBear is powered by the worker infrastructure of Cloudflare.

https://codepen.io/FlorianKoerner/pen/mdyzNjK

**Pull request merged**
