### PR TITLE
Fix collapsing b-form-select in navbar #139

### PR DESCRIPTION
**Pull request by dz-s**
Screenshot 2020-03-12 at 21 52 35
I've also tried to emulate Pixel 3, but this bug was reproduced on every display navbar was displayed on.

### CODE REVIEW

**Comment by xinbenlv** [comment]
Hi @dz-s thank you for sending this PR. I will merge it, before it allows me to do so, we will need you to explicitly sign the CLA by replying

```
@googlebot I signed it!
```

**Comment by dz-s** [comment]
@googlebot I signed it!

**Comment by xinbenlv** [comment]
@dz-s it seems the CLA bot has not yet verified the signature, I am unsure why (sorry for this additional work needed, but I am pretty sure you will only do it once.) could you do me another favor double check if you have done this

> Please visit https://cla.developers.google.com/ to sign.

**Comment by dz-s** [comment]
@googlebot I signed it!

**Comment by dz-s** [comment]
@xinbenlv np, the issue was i've signed it before but with different email (not i had in this commit). Thx.

**Pull request merged**
